### ISSUE TITLE
Update makefile and installation

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#126]
* [x] Update text on installation/environment setup instructions -> updated readme
* [x] Update help text for targets -> moved to new issue #129
* [x] Test with Python 3.9, R 4.1.3; latter to avoid recurrent warnings about R packages
* [x] Consolidate installation/setup process -> largely done: (1) install.R now redundant as all R packages moved to environment.yml (this avoids recurrent build-version errors/warnings due to conflicts between R "install.packages(package)" and "conda install r-package"), (2) most of Python packages in requirements.txt moved to environment.yml, but (3) vivarium remains in requirements.txt as moving to environment.yml causes "module not found" errors - > need to discuss; moved to new issue #130
* [x] Check whether R packages currently in install.R are available from conda-forge -> all R packages available at most current version from conda-forge except sf/r-sf (conda-forge 1.0.7, latest at CRAN: 1.0.9)
* [x] Some minor issues during testing -> moved to new issue #131

**Comment by paddy-r** [comment]
Fixed with #132

**Comment by NGRhodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make vivarium initialisation saner](https://trello.com/c/L9NhlfyM/3-make-vivarium-initialisation-saner)
