### ISSUE TITLE
Fix issues encountered during run from scratch

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#131]
Starting from clean install, some issues encountered and workarounds implemented, branched from #126. Process was: (1) Clean install of everything (conda, git, then create conda environment for both R and Python), (2) "make setup", (3) "make baseline", (4) "make aggregate_baseline_map". Final goal is to generate baseline map for Glasgow to test setup and installation.
* [x] Had to manually create "plots" folder due to error during validation/aggregate_lineplot.py (during aggregate_baseline_map) -> could add try/except block in aggregate_lineplot, but need to discuss as might be better place to do it -> moved to new issue #141.
* [x] FileNotFoundError from validation/format_spatial_output.py during aggregate_baseline_map -> moved "ADULT_population_GB_2018.csv" manually from US_spatial_lookup -> not a proper solution though, to be discussed -> to be fixed by Luke, user notes on obtaining data added to readme in #126 
* [x] FileNotFoundError, also from validation/format_spatial_output.py, no folder "minos/output/baseline" found -> hacked path to SPATIAL_DIRECTORY1, was "output/$(INTERVENTION1)", now is "output/$(DEFAULT_OUTPUT_SUBDIRECTORY)/$(INTERVENTION1)"; and same for SPATIAL_DIRECTORY2, as assuming same issue will occur; need to discuss -> fixed in #133.
* [x] Error thrown within validation/sf12_single_map.R: "object 'out.folders' not found" -> changed any reference to "out.folders" to "out.files" -> fixed errors but may not be complete solution, e.g. also may be present in validation/sf12_difference_map.R; to discuss -> to be fixed in imminent "development" update by Luke
* [x] Recurrent R errors (also see #126) for sf/r-sf due to inadvertent conflicts between "install.packages(package)" and "conda install r-package" -> fixed by uninstalling sf (remove.packages(sf) and conda uninstall r-sf) then reinstalling (conda install -c conda-forge r-sf)
* [x] Warning in sf12_single_mapR: "`aes_string()` was deprecated in ggplot2 3.0.0. / Please use tidy evaluation ideoms with `aes()`" -> to discuss; move to separate issue if necessary -> moved to new issue #140.

**Comment by RobertClay** [comment]
just responding to some of these 
1 is from file structure being changed I think. Easy to make sure the arguments in the make are correct and make the plots folder be created automatically
2 not sure you have this data? we can't make it publically available. needs a readme note somewhere about needing this I think. 
3 looks good. again issues with moving files around. 
4 not sure what this is. needs discussion. 
6 this was the only way I could get the plot to render properly. Would be amazing if you could fix it to just use aes.

**Comment by ld-archer** [comment]
Couple of things to add:
2. I've added a try except block in the `testing_development` branch that checks for the presence of the .csv file in persistent_data and prints a big help message if not found. I just said to email one of us about the missing data, and think this is the best solution for now seeing as we can't make it available.
4. The out.folders / out.files error was my fault, changed the name after testing as I thought it was more suitable and I must have forgotten to rename some things. Again fixed on the `testing_development` branch. 

I'll be PRing this branch today/tomorrow morning so these two will be fixed before long.

**Comment by paddy-r** [comment]
Closing as all points on checklist either complete or moved to separate issue for clarity.
