### ISSUE TITLE
Add parity to fertility module (ONS data + NewEthPop)

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#226]
From #167, begin by creating method using ONS data for 1934-2020 which includes parity to $p$ = 5+ and accounts for ethnicity by using *NewEthPop* data by LA or region. Rough to do list:

* [x] Some utilities for me to test grabbing Minos output at runtime -> [6472af0](https://github.com/Leeds-MRG/Minos/pull/259/commits/6472af0937882f3db6aa1c1584e9f74a0f16d1cb) and [bc84370](https://github.com/Leeds-MRG/Minos/pull/259/commits/bc843706c2d07d45899326937f38faae301bf07f)
* [x] Integrate series solver for extending geometric series; can be used on any data, but here the relevant data are births, (cohort) population and fertility -> [63be212](https://github.com/Leeds-MRG/Minos/pull/259/commits/63be212a790e4a2f5b7470e26859eac021f2f2d8)
* [x] Add more documentation to series solver as currently very opaque; it's an implementation of the Newton method -> [f4eb17d](https://github.com/Leeds-MRG/Minos/pull/259/commits/f4eb17d380fa0201f487795e85b0ee2b12d88f20)
* [x] Improve series solver functionality to allow prepending of series (i.e. solution of reverse-sorted series); trivial but not copied from Jupyter to script yet -> [3cdfb5b](https://github.com/Leeds-MRG/Minos/pull/259/commits/3cdfb5b86ffedf9537253cae0620c47b0ca8e6b8)
* [x] Streamline logic and functionality in ```utils``` and ```FertilityRateTable.extend_parity``` as may be some overlap/unclear steps, particularly when processing columns/rows with zeroes at beginning/end -> not necessary, actually fairly simple as ```utils.extend_series``` just sets extended values to zero if either of the last two values is zero, which is generally a good rule, whereas ```FertilityRateTable``` fills in zeroes if the final value is below a certain threshold, which is fertility-specific, so marking this as done as not necessary
* [x] List and document all parameters used in extending data -> done offline
* [x] Add ~~alternative method using look-up tables of fertility as function of age and parity~~ parity to look-up table generation (code already written but not integrated), i.e. F(a,p), from ONS data 1934-2020 -> will be additional, standalone method in ```FertilityRateTable``` that takes rate table without parity and expands each entry for parity -> all wrapped into ```add_parity``` method
* [x] In the above, must (1) add parity to ```build_table``` and ```register_rate_producer``` calls in ```add_new_birth_cohorts.nkidsFertilityAgeSpecificRates.setup```, and (2) add parity to ```view_columns``` (argument to ```get_view```)
* [x] Ensure ```mean_value``` is overwritten or replaced by another variable name throughout pipeline -> was a good laugh checking this, highly recommended
* [x] Add ```get_nearest``` functionality to ```apply_parity_to_newethpop``` as *NewEthPop* varies a lot by year even if ONS data don't (latest ONS year is 2020 but varies slowly with time) -> N.B. rate table is 250MB for 2011-2061! Keeping to 2020-2025 in [4b8aef5](https://github.com/Leeds-MRG/Minos/pull/259/commits/4b8aef5d396119a205b8e78295cc05fd74d971cf)
* [x] Need to confirm that ```mean_value``` - i.e. pre-parity fertility variable - is not used or required anywhere in pipeline -> remove from rate table manually and check simulation will run
* [x] Bonus points: verify that ```add_new_birth_cohort.load_age_specific_fertility_rate_data``` is indeed unused (as it says in a comment by Rob) by leaving ```mean_value``` in there and checking that Minos runs, as would throw error if it's used because ```mean_value``` has been removed from rate table
* [x] ~Also must add parity as another variable in ```BaseHandler.transform_rate_table```~ -> not necessary, as done in ```add_parity_to_newethpop```
* [x] ...however, must also differentiate ```BaseHandler.transform_rate_table``` for fertility and mortality, as parity used in fertility but not mortality -> no, not necessary for now, as parity is added to existing rate table by modifying it; however, adding to #275 in case decide to refactor ```transform_rate_table``` later
* [x] Note issues about number of children in household vs. children of individual, following discussion w/c 29/05/23; must be addressed and within remit of this issue, but already in another issue (#256), so marking as done here
* [x] Correct range of years in fertility rate table construction to exclude 2061, as data are all "NA" -> moving to #275 as neither urgent nor necessary for fertility
* [x] Following on from the above point, automate year selection (i.e. intersection of years in ONS data and NewEthPop data, happens to be 2011-2020) -> as above, moving to #275
* [x] Refactor fertility (and mortality) rate table caching to be like this: (a) cache all available NewEthPop data once only -> interim file, then (b) for each Minos run, create run-specific rate table, which doesn't need to be cached but can be (TBC) -> marking as done as put to new issue (#275)
* [x] Minos throws runtime key error if ```nkids``` for a particular individual exceeds the highest value in the fertility rate table; how to resolve -> put into #275 as doesn't prevent getting fertility with parity working
* [x] Resolve conflicts with development branch in makefile -> as suggested by Luke, pull ```development``` into this branch first, resolve stuff, then finish pull request -> conflict in makefile resolved with [2249530](https://github.com/Leeds-MRG/Minos/pull/259/commits/22495307634bacb535558b45e59c2106911da81b)
* [x] Need to resolve issue with high-parity women having children every year for entire simulation, as very high parities tend to have very high fertility -> added $n+1$ to max. parity when constructing rate table and setting last entry to zero with ```apply_max_parity``` flag in ```FertilityRateTable.apply_parity_to_newethpop``` -> circumvented with new individual parity variable, see #275 
* [x] Re. discussion on 29/06/23, confirm that Vivarium finds nearest year in rate table if exact year not present -> confirmed, tested for 2020-2025 simulation with only 2020-2021 in rate table; presumably because ```year``` variable is in ```parameter_columns``` category in ```nkidsFertilityAgeSpecificRates.setup``` (i.e. can take non-integer values)
* [x] Related to the above is what range of years Minos is likely ever going to be run over, and therefore what range should be in the cached fertility rate table -> for now cache it with 2011-2040; also done for mortality -> would also be good to be able to generate it not at runtime, so added to #275 -> settled on 2014-2040 as (1) cross-validation runs from 2014 and (2) the range 2011-2040 produces rate table file that's larger than Github's 100 MB limit
* [x] ~Big issue: Vivarium throwing ```KeyError``` because some households have more than $n$ children (as we're still using ```nkids```, which is HH, not individual), increase ```nkids_max``` to 20 for now to see if that allows all tests to run~ -> no, switch to alternative variable, covered by #256
* [x] Number of children for some women (11/29518) decreases over time; assume to be error and forward fill using cumulative max -> see ```US_missing_LOCF.mffill_groupby```

**Comment by paddy-r** [comment]
Closed with #259.
