### ISSUE TITLE
Refactor fertility/mortality rate table caching

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#275]
From #226, idea is to cache interim rate table for all available *NewEthPop* years, then generate run-specific rate table at runtime. This is motivated by the fact that the rate table currently produced (ending "_1.csv") has the same name regardless of the range of years specified in the config file, so data for years that are available in *NewEthPop* may not be in the rate table if the run during which it was created didn't cover the same period. Although this won't cause issues at runtime (as Vivarium presumably finds the nearest available year of data in the rate table), it would be good to improve it.

N.B. Already partly done in and around [1e55ca1](https://github.com/Leeds-MRG/Minos/pull/259/commits/1e55ca1865661989dae0bac614bdbd646145bd9a).

Also to do:
* [x] ~Correct range of years in fertility rate table construction to exclude 2061, as data are all "NA"~ Moving to #369
* [x] ~Following on from the above point, automate year selection (i.e. intersection of years in ONS data and NewEthPop data, happens to be 2011-2020)~ Moving to #369
* [x] ~Refactor ```transform_rate_table```, currently common to fertility and mortality; not priority~ Crossing off as waste of time
* [x] ~Cache parity rate table as slow to build~ Crossing off as not a priority
* [x] ~Allow rate table caching outside runtime; method can then also be used at runtime when necessary, but gives more flexibility~ Moving to #369
* [x] ~Issue with Minos throwing runtime key error if ```nkids``` (which is number of kids in household, see #256) exceeds maximum parity value in fertility rate table; moving here as not required to get fertility working with parity, but needs to be fixed~ -> covered by #256: new variable to replace ```nkids```
* [x] ~Think about adding try-except block to ```BaseHandler.cache``` for case of ```rate_table_path``` not being defined~ Moving to #369

**Comment by paddy-r** [comment]
Closing as everything done or moved to #369.
