### ISSUE TITLE
Refactor child poverty intervention

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#340]
Outline for simplifying interventions.

- [x] Add any required US variables not currently present, including material deprivation variables and ```nadoecd_dv``` + ```nchoecd_dv```. Done in [7fcc82f](https://github.com/Leeds-MRG/Minos/pull/345/commits/7fcc82fe884a7b738c6f49c160683a4fda8396a8).
- [x] Forward-fill variables using ```US_missing_LOCF```. Done in [c6d33b8](https://github.com/Leeds-MRG/Minos/pull/345/commits/c6d33b8590f34c382146a9a6e864fada77c89317).
- [x] Compute composite variables, including income percentile (relative and absolute) and persistent poverty counter. Done in [fc30d4a](https://github.com/Leeds-MRG/Minos/pull/345/commits/fc30d4ab124d353a82fbb2fa194667a15bb141bb).
- [x] Also add calculation of material deprivation score -> Boolean variable. -> covered by #331 but done in [fc30d4a](https://github.com/Leeds-MRG/Minos/pull/345/commits/fc30d4ab124d353a82fbb2fa194667a15bb141bb).
- [x] Add all new variables to ```replenishment```. Done in [06d7523](https://github.com/Leeds-MRG/Minos/pull/345/commits/06d752352b3a6863309a5372d8ad1060193af611).
- [x] ~~Add transition model(s) for all newly added variables (n.b. already present for ```hheat```: ```heating```).~~ Must update poverty variables, either in separate module or during intervention. Marking as done as moved to new issue #349.
- [x] Do list of all parameters, e.g. CP target number, target year (default 2030), ```target_pov_prop```, ```end_year```. Done in [bbaed37](https://github.com/Leeds-MRG/Minos/pull/345/commits/bbaed37d169fa1c8b562fee6670e47bb7d176666), see ```CONFIG_DEFAULT``` in intervention script; also can be specified in new config file.
- [x] Create config file for intervention containing (optional) arguments for intervention type and child poverty target to be addressed. Done in [42e3c85](https://github.com/Leeds-MRG/Minos/pull/345/commits/42e3c85799462ed5e6459ebf0b9e22b1949b3649).
- [x] Add default arguments to intervention module. Done, see two above.
- [x] Add ```pre_setup``` method to intervention class to allow parameters to be passed (see ```hhIncome``` intervention and fertility class). Done, see three above.
- [x] Add new make target(s) for new child poverty intervention. Done in [cafd306](https://github.com/Leeds-MRG/Minos/pull/345/commits/cafd3063e7dd6232a0959863af3f68adf60f9c26).
- [x] Refactor existing Scottish child payment method as "intervention 1". Begun in [bbaed37](https://github.com/Leeds-MRG/Minos/pull/345/commits/bbaed37d169fa1c8b562fee6670e47bb7d176666) but marking as done as moved to new issue #347.
- [x] Refactor existing SUSTAIN intervention (Target 1) as "intervention 2", as identified as priority in meeting with Emma and Gillian, 10/11/23. Begun in [bbaed37](https://github.com/Leeds-MRG/Minos/pull/345/commits/bbaed37d169fa1c8b562fee6670e47bb7d176666) but marking as done as moved to new issue #348.
- [x] NOTE: Think about adding columns for ```times_boosted``` (which then gives easy flag for finding who has been boosted), ```boosted_total``` (i.e. sum of all boosts, all years) for both individual and hh -> easy to grab for post-processing. Partly done in [bbaed37](https://github.com/Leeds-MRG/Minos/pull/345/commits/bbaed37d169fa1c8b562fee6670e47bb7d176666) but marking as done and creating new issue for clarity. -> #346
 
Begin with Target 1 (relative poverty) and reproduce functionality and output.

**Comment by paddy-r** [comment]
Closing as all jobs either done in #340 or moved to new issues.
