### ISSUE TITLE
Child poverty consolidation

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#374]
Rough to do list for immediate things to do on child poverty modelling, following PHS/SG meeting, 30/01/24.

- [x] Must develop poverty metrics slightly for different categories, prompted by looking for external data for validation (see #373) as follows: (1) by individual (i.e. all people), (2) by adult, (3) by children and (4) by household. Currently calculating (2), (3) and (4), but (2) is misnamed and (1) is important to have as a lot of external data is presented as such. Will do this on `283-moving-poverty-metrics` before merging into `283_child_uplift_generalised`. -> done in cbe89c61407eff5571f685cad4990c116f9e47c8
- [x] Ensure same method for calculating poverty metrics (i.e. percentage of hh/ind/children in each category and NOT poverty variables, which are Boolean) is consistent throughout model, preferably in a single method. -> going to claim this is done in cbe89c61407eff5571f685cad4990c116f9e47c8
- [x] Ensure all aggregation plot functionality for various variable types is combined (to include functionality in `modules.binary_plotter`, which was a workaround and not a good solution). -> done in f5b649fd5f9374b211548c49b37aed94b62c73a4, just moved `binary_plotter` for now without trying to integrate into `aggregate_lineplot`, can check if any useful functionality next time we're plotting stuff in earnest
- [x] Decide on/discuss which source of data to use for median hh income calculations. Options are (1) inter-US data, NOT synthpop (current method, but not ideal), (2) inter-US data, with synthpop (better, as would expect to match national data well) or (3) external (i.e. UK or Scottish data). Or think about running in each mode, for comparison and validation. Would expect modes (2) and (3) to yield very similar results, especially once net income module is implemented (#367). Cf. data sources in #373. -> think we've agreed to use US only for now, pending using synthpop, which *should* give results similar to UK; however, can easily switch from US data (`get_equivalised_income_internal`) to UK data (`get_equivalised_income_uk`) in `US_utils` if required; see 9f00e5b9abaadabb86f29f7c0ca5023c5649cc22 and adjacent commits
- [x] Correct `nkids` calculations in SUSTAIN and RANDOM; currently summed across individuals rather than households -> done in 834d13b39e9807cc0dec8b72b69b85d7724abe49
- [x] Deferred to `283` when pulling `285` in (see 140d323838985fb77fcd1860d541ca37c8a51bbe), so should check the following files to make sure no useful functionality missed:
    - [x] `validation/handovers.Rmd` (paths in header); `transitions/model_definitions_default.txt` (all models changed; which are correct?) -> leaving as fine, only a couple of lines, might be useful in future
    - [x] `modules/replenishment` (all poverty vars now grabbed from columns of input pop, must check all poverty vars okay throughout sim) -> no issues since then, also deleted some junk in 2bff226c9a5c858e901270c90583b254df59af80
    - [x] `data_generation/US_complete_case` (check `complete_case_vars` and block after that in `main` are okay) -> no additional type issues have arisen (cf. #352), so marking as done in 9be61f5a1de6469c29bb706ed0cdff25c2585eb7
    - [x] `data_generation/generate_repl_pop` (check typecasting okay; cf. #352). -> presumably this relates to the block in `generate_replenishing` where poverty vars are cast to `int`; marking as done as no issues since then
- [x] Pre-merge `283_child_uplift_generalised` into `283-moving-poverty-metrics`.

**Comment by paddy-r** [comment]
Moving this to separate comment to track all places that median is called...

- [x] Mean and median UK HH income statistics are calculated *by individual*, and NOT *by household*; must be corrected throughout Minos. -> done in 633423ffa371741ef2561b98b413d9cb08147710

Motivated by method of median income calculation given in ONS spreadsheet of UK hh income [here](https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/incomeandwealth/datasets/householddisposableincomeandinequality) (see note 27): "Mean and median income is calculated by assigning the equivalised household disposable income to all individuals within that household."

Places median hh income calculated in Minos below. Must all be checked and corrected, and possibly moved to a single method.

- [x] `US_utils.get_equivalised_income_internal` (was wrong)
- [x] `aggregate_subset_functions.who_below_poverty_line` and `who_relative_poverty` (already correct in the former, but edited to call common method)
- [x] `generate_composite_vars.update_poverty_vars_hh` (was wrong)
- [x] `income.lmmYJIncome.on_time_step` (correct, but replaced with common method)
- [x] `intervention` (multiple places, all of which were correct, but now use common method)

Correct process, as implemented in `US_utils.get_median` with default arguments, and to be called from everywhere above, is:

1. Filter for alive individuals
2. Calculate median income *across all individuals*, not *across households*
