### ISSUE TITLE
Full GB synthpop for fertility - final tasks

### ISSUE THREAD

**Issue by paddy-r** [Leeds-MRG/Minos#464]
Sweeping up several lower priority tasks from other places, plus a couple of new ones to draw a line under retaining full US population, generating all-GB synthpop for 2020 (Minos 2019) and generating all metrics necessary for fertility write-up.

- [x] Add basic fertility metrics (and mortality metric): mortality, total fertility rate (TFR), general fertility rate (GFR), crude birth rate (CBR) and reference data; all in notebooks ready to be copied over. -> done in [04dfeb7](https://github.com/Leeds-MRG/Minos/pull/455/commits/04dfeb768c3605572a6200ed10a9be268d977f68) and [31eb953](https://github.com/Leeds-MRG/Minos/pull/455/commits/31eb953073f115bb66e16fd5cfec8b4de812e9e5)
- [x] Ensure synthpop has correct regions, i.e. mapped from LSOAs/DZs, rather than from US. -> done in [14925f8](https://github.com/Leeds-MRG/Minos/pull/455/commits/14925f8bb8a37b4c12fe944fac823fe069d50783), code was already present in `utils.add_spatial_attributes`
- [x] Add some spatial plotting functionality, e.g. birth rate by region. -> basics done in [96ceadf](https://github.com/Leeds-MRG/Minos/pull/455/commits/96ceadf373cbd138a44acfd7b6d6c5afbe884478) and [389da41](https://github.com/Leeds-MRG/Minos/pull/455/commits/389da41ce50268a0c6a75d0b699008bbde56257d)
- [x] Allow for particular fertility metric to be matched to reference data at first year of simulation; this avoids initial-value problems. Could use general fertility rate (GFR), crude birth rate (CBR) or total fertility rate (TFR), as in figure below from pared-down microsim (not Minos). -> marking as done here as covered in dedicated issue/PR (#484/#485)

![metrics](https://github.com/Leeds-MRG/Minos/assets/50209911/13f339e8-06e3-43c2-b3fd-a7fa9905e50c)

- [x] Add ~runtime and~ post-processing functionality to analyse particular groups (e.g. age brackets, ethnicity). -> nuts and bolts done in #487/#488
- [x] Add functionality for (e.g.) cohort-based fertility rates and average birth spacing for validation with (e.g.) Frejka and Sardon (2007).
  - [x] Birth spacing. -> first attempt at birth spacing and related metrics done in [e6001f5](https://github.com/Leeds-MRG/Minos/pull/454/commits/e6001f5fd7ad8f408b806f06ff105b8f1295cab7); done up to spacing 3, including visualisation, in #487/#488
  - [x] Cohort-based fertility rates. -> nuts and bolts done in #487/#488; can select cohort arbitrarily using (e.g.) argument to `fertility_utils.get_metrics_post`, also see age bin/bracket specification in ASFR methods
- [x] Allow synthpop size to be specified in config file(s); will need input population to be created and tested on four fertility suite baseline runs (e.g. 1, 5, and 10%). -> done up to 5% in [2f08d74](https://github.com/Leeds-MRG/Minos/pull/455/commits/2f08d7456711444d6b319886fc150231b58aefbb), but not possible locally at 10% as not enough memory
- [x] Remove any pre-simulation calculation of replenishing population from pipeline for synthpop as unnecessary - ~all~ partly done at runtime in #482/#483; fully done in [680419f](https://github.com/Leeds-MRG/Minos/pull/455/commits/680419fe0ac75dff94ef4cb3461eec568b6888ad) and [bb5e2cc](https://github.com/Leeds-MRG/Minos/pull/455/commits/bb5e2ccb82f85cff1a1e333b39e5cba6a793f3aa)
- [ ] Generate additional years of synthpop input (e.g. 2019-2021/Minos 2018-2020, as in IE (II)) (from #456).
- [x] Check and correct all fertility metrics. -> marking as done here as covered by #487 
- [ ] Check all births and fertility functionality being calculated/updated correctly, both before and at runtime. (Detail to be added later.)
  - [ ] Must ensure `child_ages_ind` correct everywhere as negative values present.
- [ ] Ensure consistent years of data being selected everywhere. Follow-up to point in #456. Minos years off by one; must ensure offset used when (a) getting rate tables (fertility and mortality) and (b) comparing to reference data, i.e. fertility rates, for validation.
- [x] Make sure replenishing population is suitable for individual-level synthpop. Currently creates households for 16yos. -> marking as done here, as covered in #482
